### ISSUE TITLE
Custom Rule in Workspace?

### ISSUE THREAD

**Issue by conkpb-cg** [DavidAnson/vscode-markdownlint#160] opened 2021-04-26 14:07 UTC
I've created a VSCode workspace and I'm trying to use a custom rule, `markdownlint-rule-emphasis-style-1.0.1`, that I have working in the folders.

```json
		"markdownlint.customRules": [
			".vscode/markdownlint-rule-emphasis-style-1.0.1"
		],
```

However, I'm getting this error

```bash
[8:58:13 AM] ERROR: Exception while linting:
Error: Cannot find module '.vscode/markdownlint-rule-emphasis-style-1.0.1'
Require stack:
- c:\Users\conkpb\.vscode\extensions\davidanson.vscode-markdownlint-0.40.4\bundle.js
- c:\Users\conkpb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
...
```

I've copied the `.vscode/markdownlint-rule-emphasis-style-1.0.1` folder to the same folder as my `code-workspace` file.

Am I doing something wrong?

**Comment by conkpb-cg** [comment] 2021-04-26 14:11
Sorry. I have a problem in the underlying folder for some reason....

**Comment by DavidAnson** [comment] 2021-04-26 14:52
Can you point to a repo that shows the problem? Is there an index.js or package.json in the custom rule folder? You say it works elsewhere? What's that scenario?

**Comment by DavidAnson** [comment] 2021-04-26 14:53
Also, what version of VS Code and the markdownlint extension?

**Comment by conkpb-cg** [comment] 2021-04-26 15:02
Thanks for the prompt reply to a vague question.

- VSCode: 1.55.2
- markdownlint extension: 0.40.4
- Custom rule: https://www.npmjs.com/package/markdownlint-rule-emphasis-style

The  repo is behind a firewall so I can not share it. I can show you the settings file. As I said it has not changed.

![image](https://user-images.githubusercontent.com/60627763/116104793-5e194c00-a676-11eb-96a9-9251b8696f16.png)

This is a c# repo so it has no index.js or package.json.

**Comment by conkpb-cg** [comment] 2021-04-26 15:05
The repo folder structure is as you would expect and hasn't changed:

![image](https://user-images.githubusercontent.com/60627763/116105465-f6173580-a676-11eb-9171-9ff6add1ef93.png)

**Comment by DavidAnson** [comment] 2021-04-26 15:07
I was asking about index/package in the custom rule folder. I can try to set up a reproduction tonight. For now, could you please try switching to extension version 0.40.3 just to be sure this isn't a regression? 0.40.even lints using a totally different mechanism and I've had a couple of surprises already. You can change versions in the extension tab of VS Code under the "..." menu.

**Comment by conkpb-cg** [comment] 2021-04-26 15:14
That I can do.

[package.zip](https://github.com/DavidAnson/vscode-markdownlint/files/6378220/package.zip)

It should be the same as in: https://www.npmjs.com/package/markdownlint-rule-emphasis-style

**Comment by conkpb-cg** [comment] 2021-04-26 15:16
🚨 @DavidAnson Yes, using 0.40.3 fixed it. You have a regression.

![image](https://user-images.githubusercontent.com/60627763/116107242-78542980-a678-11eb-87f9-6143c9202f82.png)

**Comment by DavidAnson** [comment] 2021-04-26 15:22
Darn, thanks. Stick with the previous version for now and hopefully this doesn't blow up before I can look/fix tonight.

**Comment by DavidAnson** [comment] 2021-04-27 04:18
Please prefix the path to the custom rule with `./` to indicate that it is a file path relative to the base folder. From your example: `./.vscode/markdownlint-rule-emphasis-style-1.0.1`. Please let me know if this does/not work.

This is due to the behavior of Node's `require()` and described in the second-to-last paragraph here: https://nodejs.org/dist/latest-v14.x/docs/api/modules.html#modules_file_modules

You've established this is a behavior change and it wasn't immediately clear to me, but I think the new behavior is better because it allows resolving custom rules as core modules (never going to happen) or package names from `node_modules` (handy and I've used this!).

Assuming it works for you with the change, I'll update the breaking change notes for `0.40.x` to mention this.

**Comment by DavidAnson** [comment] 2021-04-27 04:19
By the way, I think adding the `./` is backwards-compatible with previous versions of the extension, so it's the preferred (unambiguous) syntax.

**Comment by conkpb-cg** [comment] 2021-04-27 13:55
> Please let me know if this does/not work.

Yes, that workaround fixed it.

Just to be clear, you intend to keep the breaking change?

No disagreement that it's better. You may need to document and possible use a full path or some other details in your error message so the required usage of `./` is discoverable.

Many thanks for maintaining this tool. It's vital.

**Comment by DavidAnson** [comment] 2021-04-27 14:37
Yes, I'll add documentation in order set to resolve/close this issue.

**Closed** 2021-04-28 04:32 UTC
Labels: question
