### ISSUE TITLE
Exception while linting with markdownlint-cli2

### ISSUE THREAD

**Issue by aNickzz** [DavidAnson/vscode-markdownlint#190] opened 2021-09-20 01:39 UTC
This just started happening while any markdown file is open in a devcontainer.

```
[11:01:12 am] ERROR: Exception while linting with markdownlint-cli2:
Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
```

<details>
<summary>trace</summary>

```
	at S (c:\Users\nicho_b0y3ef3\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:67:40822)
	at new f (c:\Users\nicho_b0y3ef3\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:67:41642)
	at new p (c:\Users\nicho_b0y3ef3\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:67:43290)
	at p.with (c:\Users\nicho_b0y3ef3\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:67:42336)
	at j (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:1:1047)
	at H (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:1:1200)
	at Object.Y (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:1:1462)
	at Object.t.read (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:106905)
	at a.t.stat [as _stat] (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:106650)
	at c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:128072
	at new Promise (<anonymous>)
	at a._getStat (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:128046)
	at a._getEntry (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:127929)
	at PassThrough.s._write (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:127742)
	at writeOrBuffer (internal/streams/writable.js:358:12)
	at PassThrough.Writable.write (internal/streams/writable.js:303:10)
	at a.static (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:127882)
	at i.api (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:119931)
	at c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:119766
	at new Promise (<anonymous>)
	at i.read (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:119732)
	at Array.map (<anonymous>)
	at u (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:117458)
	at l (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:15:117296)
	at c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:21:5402
	at Array.map (<anonymous>)
	at e.exports (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:21:5394)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:37:2026
	at async C (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:37:1769)
	at async T (c:\Users\nicho_b0y3ef3\.vscode-insiders\extensions\davidanson.vscode-markdownlint-0.44.0\bundle.js:37:5811)
```

</details>

Running in a docker dev container, this error occurs and forces focus to the "Output" panel by the terminal. When i try to click away to focus the Terminal tab or the Ports tab (which I've moved down by the terminal too) it errors again forcing focus back to Output, meaning I can't use the terminal so long as a (saved) markdown file is open (even if the file is empty).

```yml
Name: markdownlint
Id: davidanson.vscode-markdownlint
Description: Markdown linting and style checking for Visual Studio Code
Version: 0.44.0
Publisher: David Anson
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
```

**Comment by DavidAnson** [comment] 2021-09-20 03:17
The trace says you are using an Insiders build. Does it also happen with the official build? And what steps can I follow to reproduce this? I don't know what you mean by "running in a Docker devcontainer".

**Comment by DavidAnson** [comment] 2021-09-20 03:21
This contributed fix should prevent the output window from taking focus, not sure why that's happening here: https://github.com/DavidAnson/vscode-markdownlint/commit/a92439f6c90ddfdaf972967712de8aff1f864973

**Comment by DavidAnson** [comment] 2021-09-20 03:29
Found the dev container documentation: https://code.visualstudio.com/docs/remote/containers. Would still love to know the steps to reproduce, thanks.

**Comment by DavidAnson** [comment] 2021-09-20 03:43
I followed the steps here using Code Insiders and version 0.44.0 of the vscode-markdownlint extension and I'm able to open Markdown files inside the dev container and create/fix linting violations without the issue you report: https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume

In my case, the markdownlint extension is installed locally and I'm using the latest Remote - Containers extension (also installed locally). The dev container has only the ESLint extension since that comes by default.

**Comment by DavidAnson** [comment] 2021-09-20 18:33
Sorry for the trouble! I've just published version 0.44.1 which is identical to the previous version 0.43.2. I will investigate a couple of bug reports and re-release the new version with fixes soon.

Note: The other issues are clear about how to reproduce - for this one I still need steps per above. Thank you!

**Comment by aNickzz** [comment] 2021-09-23 05:08
Hi sorry for the delay in my reply, I've tried to reproduce this but I haven't been able to.

After raising this issue I closed the markdown files and promptly forgot about it as I haven't needed to edit any markdown files for a while.

I'm in the same dev container as I was using before and I'm not having any trouble. It may have been a one-off thing perhaps with my computer at the time or maybe something in the dev container failed to initialize properly.

**Comment by DavidAnson** [comment] 2021-09-23 05:24
Thanks for trying! It may be that you got auto upgraded to the patch release I did to revert to the previous version. If you get bored and want to try after forcing the install of version 0.44.0, there may be a legitimate issue here. At the same time, I will soon have a refactoring of some of the relevant code to fix another issue. That will be part of the next update and I'm hopeful it will also resolve your problem. Of course, I'd love to be sure, so please do let me know if you find a way to reproduce this. Thanks!

**Comment by DavidAnson** [comment] 2021-09-25 03:02
I can reproduce that error message with GistPad on Windows, will fix that and hope it's the same thing you were seeing.

**Closed** 2021-09-25 23:11 UTC
Labels: bug, fixed in next

**Comment by OldStarchy** [comment] 2021-09-29 05:05
Ah so I'm not going crazy (yet).

Not sure what version I was running at the time of my second comment, but currently on v0.44.3. Thanks for your help.
