### ISSUE TITLE
Files saved on UNC paths do not get linted

### ISSUE THREAD

**Issue by SheffSix** [DavidAnson/vscode-markdownlint#216] opened 2021-12-16 12:08 UTC
markdownlint v0.45.0
VSCode v1.63.1
Windows 10 Education 20H2

As the title says - files opened from a UNC path have no lint applied. Opening the same file from a mapped drive works perfectly.

There are no custom settings applied currently. This is a fresh install of VSCode and I have tested with a brand new markdown file in an empty directory.

I can't see any useful information in the Output window of VSCode and, in all honesty, I'm a newbie to VSCode so I have no idea where to look for any other logs there may be.

UNC Path:
![unc](https://user-images.githubusercontent.com/26144059/146369075-a0f6740b-b84c-4aff-9aa8-a4c9613d07c7.png)

Mapped drive:
![mapped](https://user-images.githubusercontent.com/26144059/146369086-fb0047bd-d4e7-497b-be70-c69d58a82fc2.png)

**Comment by DavidAnson** [comment] 2021-12-16 18:13
This was a problem, but was confirmed fixed in #196.  Any chance you are seeing #215 instead? If not, can you please be a little more specific about whether it's all UNC paths or something in particular?

**Comment by SheffSix** [comment] 2021-12-16 18:50
It seems to be any UNC path. I tried it on a few shares. Initially I was
working on a hidden share, with a $ at the end, but I created a new share
without to try it - same result.

**Comment by DavidAnson** [comment] 2021-12-16 19:06
Does the path look like `\\server\share\file.md`? Can you share what's in the Output panel's "markdownlint" section?

**Comment by SheffSix** [comment] 2021-12-16 19:10
Yes, exactly that. The output literally just says that it is going to lint
the file, nothing more. I'll screenshot when I'm back at work tomorrow

**Comment by DavidAnson** [comment] 2021-12-16 21:54
Sorry about that, I tried on Windows and I can reproduce this behavior so I don't need anything else from you. The problem is that this function is combining `//server/share` and `file.md` into `/server/share/file.md`: https://github.com/DavidAnson/vscode-markdownlint/blob/5b420856f9701ba8245ee6b1d00c3e4b1ded7360/extension.js#L90

Losing that leading slash causes path problems elsewhere. Overriding the current behavior produces the desired result. As I recall, that's exactly how this worked previously and that's why my earlier fix worked. So I want to say this is a behavior change in VS Code's implementation of that API, but it's not worth it to me to go back and verify.

The good news is that my idea for how to fix the parentheses problem involves removing this function entirely and I'm optimistic that will implicitly fix this problem. If not, I will look for a dedicated fix. I hope to have this in the next update in a few weeks. Thanks for your help!

**Closed** 2022-01-31 03:18 UTC
Labels: bug, fixed in next
