### ISSUE TITLE
Default settings being written automatically

### ISSUE THREAD

**Issue by craigktreasure** [DavidAnson/vscode-markdownlint#206] opened 2021-11-05 20:57 UTC
Using v0.45.0, i've noticed that this very helpful extension has begun editing or creating `settings.json` with the following settings:
```json
  "markdownlint.config": {
    "MD028": false,
    "MD025": {
      "front_matter_title": ""
    }
  }
```

I don't know if this was intentional or not, but it has become quite obnoxious to have these settings added to any project I open, even though I haven't explicitly made any effort to customize the settings myself. This has caused the change above to be made to all existing `settings.json` files as well as to create new `settings.json` files when one doesn't already exist. This results in unintentional changes to the working directory. This doesn't seem necessary for default settings, but i'd be curious to understand otherwise.

**Comment by nschonni** [comment] 2021-11-05 22:12
Duplicate of https://github.com/DavidAnson/vscode-markdownlint/issues/204

**Comment by DavidAnson** [comment] 2021-11-06 00:49
Yes, please open an issue for that extension.

**Closed** 2021-11-06 00:49 UTC
