### ISSUE TITLE
ERROR: Exception while linting with markdownlint-cli2 using ignores in a configuration file

### ISSUE THREAD

**Issue by borekb** [DavidAnson/vscode-markdownlint#195] opened 2021-09-26 20:16 UTC
After the latest update, I'm getting this error in the Output panel:

```
[10:13:42 PM] ERROR: Exception while linting with markdownlint-cli2:
EntryNotFound (FileSystemError): Unable to resolve non-existing file '/Users/borekb/dev/shoptet/sofa/!**/node_modules/**'
    at _handleError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:160087)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This is my `.markdownlint-cli2.js` (that used to work before):

```js
require('./.pnp.cjs').setup();

const path = require('path');

module.exports = {
  config: {
    MD007: {
      indent: 4,
    },
    MD013: false,
    MD014: false,
    MD040: false,
    MD029: false,
    MD033: false,
    MD026: false,
    MD009: { br_spaces: 0 },
    MD031: { list_items: false },
    'graphql-examples': {
      schema: path.join(__dirname, 'packages/graphql/schema.graphql'),
      globs: [`${__dirname}/docs/docs/**/*.md{,x}`],
    },
  },
  ignores: ['**/node_modules/**', '**/.next/**', '**/dist/**'],
  customRules: ['@shoptet-private/markdownlint-graphql-examples'],
};

```

**Comment by DavidAnson** [comment] 2021-09-26 20:22
As a hack for the VS Code experience, I think you can comment out the "ignores" section (which isn't very relevant there anyway).

**Comment by borekb** [comment] 2021-09-26 21:47
Thanks but we use the same config for CLI invocation and for VS Code as well so we cannot really remove the `ignores` section without further changes. Will probably wait for a fix instead 😄.

**Comment by commputethis** [comment] 2021-09-26 21:52
I'm having a similar issue after this last update.  I kind of assume it is the same, but the error is a little different.

![image](https://user-images.githubusercontent.com/17625274/134825420-117d0b10-5088-4a92-adee-0dea0be3caf4.png)

**Comment by commputethis** [comment] 2021-09-26 22:30
not sure if it would help or not, but here is the file I have open that is giving the error
[README.md](https://github.com/DavidAnson/vscode-markdownlint/files/7232392/README.md)
s.

**Comment by DavidAnson** [comment] 2021-09-26 22:32
@borekb, I said it was a hack. :) I'll look into this tonight.

@commputethis, it's hard to say if it's the same since the path is blocked out in your image. That may be how this problem shows up on Windows (original report is Mac), or it may be something else. If you are not using `ignores`, it is probably something else. Steps to reproduce would be very helpful!

**Comment by commputethis** [comment] 2021-09-26 22:33
the path blocked out is just the path to the readme.md file I uploaded

**Comment by DavidAnson** [comment] 2021-09-26 22:39
@commputethis That's something else, could you please open an issue? It's not to do with the content of the Markdown file, but something to do with the path or location of the configuration files involved. If you can please share the repository or show how to reproduce myself in a new folder, that would be great! Is this all local file system, or is it going through a virtualized file system? Are there any unusual characters in the path?

**Comment by commputethis** [comment] 2021-09-26 22:43
I can open a separate issue, but the file path is a network unc path

**Comment by commputethis** [comment] 2021-09-26 22:45
oh, I see the issue now that I actually read the file path listed.  it is like \\servername\servername\share.  The servername is there twice for some reason.

**Comment by DavidAnson** [comment] 2021-09-26 22:45
@commputethis LOL, of course it's a UNC path. Because the other 30 scenarios I'm testing with aren't enough to deal with. :)

**Comment by DavidAnson** [comment] 2021-09-26 22:47
@commputethis I'd guess you can work around this for now with `net use` to make it a drive letter.

**Comment by DavidAnson** [comment] 2021-09-26 22:48
@commputethis Very helpful, thanks!

> \servername\servername\share

**Comment by commputethis** [comment] 2021-09-26 22:49
I opened a new issue for this https://github.com/DavidAnson/vscode-markdownlint/issues/196

**Comment by DavidAnson** [comment] 2021-09-27 04:38
This (the original issue, not the problem with network shares which I hope is an extreme edge case I'll look into shortly) should be fixed in 0.44.3. There's no associated fix commit because I did something shady in order to get the fix out sooner. I'm leaving this issue open and will resolve it with the proper commit soon.

**Comment by DavidAnson** [comment] 2021-09-28 04:55
CLI2 commit for this: https://github.com/DavidAnson/markdownlint-cli2/commit/5d58f81cfbd748aaca77bb7cef31a74664a86c31.

**Comment by borekb** [comment] 2021-09-28 07:05
@DavidAnson Can confirm that the behavior in VSCode is now correct, thanks!

**Closed** 2021-10-03 19:12 UTC
Labels: bug, fixed in next
