### ISSUE TITLE
Markdown lint errors when opening Codespaces

### ISSUE THREAD

**Issue by pamelafox** [DavidAnson/vscode-markdownlint#325] opened 2024-02-14 16:14 UTC
I got these errors in several Codespaces this morning:

```
[4:11:53 PM] ERROR: Exception while linting with markdownlint-cli2:
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
    at C (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:7116)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at I (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:12216)
    at R (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:14818)
[4:11:53 PM] ERROR: Exception while linting with markdownlint-cli2:
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
    at C (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:7116)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at I (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:12216)
    at R (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:14818)
[4:11:54 PM] ERROR: Exception while linting with markdownlint-cli2:
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
    at C (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:7116)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at I (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:12216)
    at R (/home/vscode/.vscode-remote/extensions/davidanson.vscode-markdownlint-0.54.0/bundle.js:37:14818)
```

When opening these in Codespaces:
https://github.com/pamelafox/django-quiz-app/
https://github.com/pamelafox/simple-flask-server-example/
https://github.com/pamelafox/flask-db-quiz-example/

**Comment by DavidAnson** [comment] 2024-02-14 17:03
Duplicate of external issue #264, sorry. Steps to fix are linked there.

**Comment by pamelafox** [comment] 2024-02-14 17:22
Ah got it! I had the setting in my settings, and I had setting sync on. Removed the setting as described there. Thanks!

**Closed** 2024-02-14 17:52 UTC
Labels: question
