### ISSUE TITLE
MD037/no-space-in-emphasis after LaTeX formula

### ISSUE THREAD

**Issue by srezasm** [DavidAnson/vscode-markdownlint#289] opened 2023-07-02 07:15 UTC
When using the double underscore (__) as an emphasis marker in Markdown, the linter raises the "MD037/no-space-in-emphasis" warning even though there is no space between the emphasis (_)s and the surrounded texts.

The reason is that earlier in the same line, I used a (_) in the LaTeX formula to make a subscript.

Problematic paragraph:  
`$J_{train}$ is the fraction of _training set_ that has been misclassified.`

Display style:  
$J_{train}$ is the fraction of _training set_ that has been misclassified.

**Comment by DavidAnson** [comment] 2023-07-02 15:49
Duplicate of this issue for the library: https://github.com/DavidAnson/markdownlint/issues/597

**Comment by DavidAnson** [comment] 2023-09-18 04:32
[Re-posting this comment GitHub seems to have lost]

This issue is fixed in the latest version of the `markdownlint` library which will be used by the upcoming release of this extension.

https://dlaa.me/markdownlint/#%25m%23%20Issue%20289%0A%0A%24J_%7Btrain%7D%24%20is%20the%20fraction%20of%20_training%20set_%20that%20has%20been%20misclassified.%0A

**Closed by DavidAnson** 2023-09-18 04:32 UTC
Labels: question
