### ISSUE TITLE
ERROR: Implicit map keys need to be on a single line

### ISSUE THREAD

**Issue by tyler36** [DavidAnson/vscode-markdownlint#198] opened 2021-10-01 04:05 UTC
Thank you for this extention. It works great in WSL2 during normal usage.

I have a problem when I use this with the [Github Pull Request and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extenstion.

When I create a new issue via Github Pull Request and Issues,  it opens up a new `\NewIssue.md`.  This generates the following error in the Output panel:

```
[12:58:29] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse '/.markdownlint.jsonc'; Unexpected token I in JSON at position 0; Implicit map keys need to be on a single line
	at /home/user13/.vscode-server/extensions/davidanson.vscode-markdownlint-0.44.3/bundle.js:33:27234
	at /home/user13/.vscode-server/extensions/davidanson.vscode-markdownlint-0.44.3/bundle.js:1:1504
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by DavidAnson** [comment] 2021-10-01 05:01
This looks a lot like #194 which should be fixed in extension version 0.44.3 and later. Can you please check that you have the latest version? If so, could you please list the steps to reproduce this? Is it necessary to use WSL2? Is opening a new issue without a folder open sufficient?

**Comment by DavidAnson** [comment] 2021-10-01 05:14
Thinking about this a little, it may still be present in the latest version because this scenario uses a different extension which may be doing the same problematic thing as in the other issue. If so, there shouldn't be any dependency on WSL and you should be able to reproduce this just by creating a new issue.

**Comment by tyler36** [comment] 2021-10-01 06:01
Sorry, I forgot to include in my OP.

VSCode: 1.60.2
Markdownlint: 0.44.3

ENV:
Remote-WSL: 0.58.2
Git Pull Requests & Issues: 0.30.0
OS: WSL2 (Ubuntu)

**Comment by tyler36** [comment] 2021-10-01 06:38
OK ... testing with a clean version of VSCode witho

VSCode: 1.60.2
Markdownlint: 0.44.3
Git Pull Requests & Issues: 0.30.0
OS: Win10 (not WSL2)

After I  click "Create an Issue"
- The OUTPUT panel is focused with the following error:
```
[3:20:38 pm] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse 'D:/.markdownlint.jsonc'; Unexpected token I in JSON at position 0; Implicit map keys need to be on a single line
	at d:\portable\Webdev\VSCode\data\extensions\davidanson.vscode-markdownlint-0.44.3\bundle.js:33:27234
	at d:\portable\Webdev\VSCode\data\extensions\davidanson.vscode-markdownlint-0.44.3\bundle.js:1:1566
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
- If I type something, the following INFO is appended:
```
[3:21:56 pm] INFO: Linting for "newIssue:/NewIssue.md?%7B%22origin%22%3A%22file%3A%2F%2F%2Fd%3A%2Fcode%2Flaravel%2Fsites%2Fiq-community%22%7D" will be run "onType".
```
- closing the `NewIssue` file and attempting to open another new issue does nothing. The original error does *not* appear again.
- If I "reload window", or restart Vscode, the original problem re-occures.

## testing linting
- In the '\NewIssue.md' file, I write "bad" markdown to trigger the problem lightbulb

```markdown
# Title
- example
```
- Selecting the lightbulb and "Fix all supported markdownlint violations in the document" results in the following message in the OUPUT panel:

```
[3:28:33 pm] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse 'D:/.markdownlint.jsonc'; Unexpected token I in JSON at position 0; Implicit map keys need to be on a single line
	at d:\portable\Webdev\VSCode\data\extensions\davidanson.vscode-markdownlint-0.44.3\bundle.js:33:27234
	at d:\portable\Webdev\VSCode\data\extensions\davidanson.vscode-markdownlint-0.44.3\bundle.js:1:1566
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It looks like markdownlint is having problems with the path. 
- the project is located at `D:\code\laravel\sites\iq-community`
- the path of the `NewIssue.md` is `\NewIssue.md`; via shift+alt+c shortcut for "copy path"

Hope this helps.

**Comment by DavidAnson** [comment] 2021-10-01 15:27
Awesome, thank you! I'll be looking at this tonight.

**Closed** 2021-10-03 19:12 UTC
Labels: bug, fixed in next

**Comment by tyler36** [comment] 2021-10-04 00:45
Thank you. 

- Error does not appear in `0.44.4`
- Linting no longer works in file (works as designed)
