### ISSUE TITLE
Extension does not seem to work on Ubuntu, on WSL

### ISSUE THREAD

**Issue by piotrminkina** [DavidAnson/vscode-markdownlint#308] opened 2023-11-12 20:28 UTC
Hello,

I'm using VSCode 1.84.2 with markdownlint extension in version 0.52.0 on Windows 11 Pro. With below `.markdownlint.json` all works fine, when my project is developed directly on Windows.

```json
{
  "default": true,
  "MD012": {
    "maximum": 3
  },
  "MD022": {
    "lines_above": 2,
    "lines_below": 1
  }
}
```

But when I open the same project via WSL connection on Ubuntu 22.04, exception are thrown.

```
[9:13:28 PM] ERROR: Exception while linting with markdownlint-cli2:
AggregateError: Unable to require or import module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'.
	at A (/home/piotrek/.vscode-server/extensions/davidanson.vscode-markdownlint-0.52.0/bundle.js:37:6929)
	at async Promise.all (index 0)
	at async Promise.all (index 0)
	at async N (/home/piotrek/.vscode-server/extensions/davidanson.vscode-markdownlint-0.52.0/bundle.js:37:9881)
	at async R (/home/piotrek/.vscode-server/extensions/davidanson.vscode-markdownlint-0.52.0/bundle.js:37:14432)
```

This is basically a clean installation of Ubuntu, from the MS Store. Maybe it is missing some dependency?

Regards
Piotr Minkina

**Comment by DavidAnson** [comment] 2023-11-12 20:44
Duplicate of external issue #264. Steps to fix are linked there.

**Closed** 2023-11-28 07:37 UTC
Labels: question
