### ISSUE TITLE
Legitimate trailing hash char triggers MD003 and MD020

### ISSUE THREAD

**Issue by mikesigs** [DavidAnson/vscode-markdownlint#35] opened 2018-04-01 05:58 UTC
If there is a header where you actually want to finish with a '#', there appears to be no way to escape this, or ignore the triggered rules. Apart from changing the header style for the whole document to be atx_closed.

Example: 
### I love F#
or 
### 10 Reaons to Use F#

Triggers the following warnings:
- MD003/header-style: Header style [Expected: atx; Actual: atx_closed]
- MD020/no-missing-space-closed-atx: No space inside hashes on closed atx style header

Perhaps the linter could check the number of trailing hash characters, and if it's just one but the header  starts with two or more, it could ignore the usage? 

This would still result in a MD003 for level-1 headers though, where atx style was in use throughout the rest of the document.

**Comment by mikesigs** [comment] 2018-04-01 06:29
Thanks for the ridiculously fast response man! However, that doesn't seem to work for me. 

![image](https://user-images.githubusercontent.com/811177/38170478-bf365a66-3543-11e8-8791-b4da879a9aa9.png)

**Comment by DavidAnson** [comment] 2018-04-01 20:10
Sorry for the trouble! Although "F\#" makes `MD020` go away as discussed in the linked issue, `MD003` remains. Looking briefly, I think the issue is in `headingStyleFor`. I should be able to fix this soon.

**Comment by mikesigs** [comment] 2018-04-02 06:00
No trouble at all man. It's just a harmless squiggly :) 
Thanks for taking the time to respond and look at a fix!

**Comment by DavidAnson** [comment] 2018-04-28 21:52
This is fixed by https://github.com/DavidAnson/markdownlint/commit/017fe127fa987bea83c948efb7cb00d5fd54546e in the `markdownlint` project and will be included here with the next dependency update.

**Comment by DavidAnson** [comment] 2018-06-01 04:59
Fixed by https://github.com/DavidAnson/vscode-markdownlint/commit/1037d63a8d7f0bc1cc247b316740b295d0299043 in this project, likely to be published tomorrow.

**Comment by DavidAnson** [comment] 2018-06-02 05:26
Now available in `0.18.0`.

**Closed by DavidAnson** 2018-06-02 05:26 UTC
Labels: bug
