### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by IanKensey** [DavidAnson/vscode-markdownlint#173] opened 2021-06-25 16:48 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-markdownlint`
- Extension Version: `0.42.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\iank\AppData\Local\Temp\DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DavidAnson** [comment] 2021-06-25 16:51
Could you please attach the file referenced above?

**Comment by IanKensey** [comment] 2021-06-25 18:37
[DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt](https://github.com/DavidAnson/vscode-markdownlint/files/6718177/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt)

**Comment by IanKensey** [comment] 2021-06-25 18:38
This issue is now preventing me from making changes on a number of essential changes that I need to have done ASAP.

**Comment by IanKensey** [comment] 2021-06-25 18:42
[DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt](https://github.com/DavidAnson/vscode-markdownlint/files/6718185/DavidAnson.vscode-markdownlint-unresponsive.cpuprofile.txt)
This is the latest data file.  Nothing I seem to do is making the slightest bit of difference.

**Comment by DavidAnson** [comment] 2021-06-25 18:42
You can disable or uninstall the extension in VS Code and any role it's playing in your scenario will go away.

**Comment by IanKensey** [comment] 2021-06-25 18:43
I'm authoring docs, and using docsAuthoringPack, which needs this extension.  Because it fails, all the associated DocsAuthoring also fail. Which is now preventing me from working.

**Comment by IanKensey** [comment] 2021-06-25 18:44
I've tried disabling DocsAuthoring, but that doesn't fix the problem because then I can't use any of the tools.

**Comment by DavidAnson** [comment] 2021-06-25 18:56
As I understand, the Docs Authoring extension includes this one by reference, but does not require it.

What's the issue you are seeing? This performance warning typically just means VS Code was a little slow to start.

**Comment by DavidAnson** [comment] 2021-06-25 19:06
If it's not startup, I guess this could be an infinite loop on some Markdown file? If so, closing all files in VS Code should stop the problem since this extension only looks at open files. Then open files one-by-one to find the one causing the problem.

**Comment by IanKensey** [comment] 2021-06-25 20:14
I found the problem.  When using the :::image::: tag, and the type is "complex" and it doesn't have the closing :::image::: it causes your extension to stop running properly.   Hope this helps.

**Comment by DavidAnson** [comment] 2021-06-25 20:17
Tags are not something this extension is aware of (at least without a plug-in). Can you provide a sample document or repository? I'll fix the issue if I can tell what it is!

**Comment by DavidAnson** [comment] 2021-06-25 21:22
This issue appears to have been mis-attributed by VS Code. I looked at both of your traces and the one function that's taking all of the time is coming from the docs-linting extension: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-linting. Unsurprisingly based on your comment about the “image” tag, the relevant file is file:///c:/Users/iank/.vscode/extensions/docsmsft.docs-linting-0.0.7/markdownlint-custom-rules/image.js which corresponds to this part of the docs-linting extension: https://github.com/microsoft/vscode-docs-authoring/blob/main/packages/docs-linting/markdownlint-custom-rules/image.js. My guess is that one of the arrow functions in the forChild function is looping infinitely in your scenarios. Please open an issue in their repository and include the steps to reproduce it if possible. Thanks!

**Closed** 2021-06-25 21:23 UTC
Labels: question
