### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by ChristopherGLewis** [DavidAnson/vscode-markdownlint#175] opened 2021-07-08 16:32 UTC
I am continuously getting exception errors:

```
[11:28:00 AM] ERROR: Exception while linting:
Error: Cannot find module 'c:/Users/ChrisLewis/.vscode/extensions/docsmsft.docs-markdown-0.2.95/markdownlint-custom-rules/rules.js'
Require stack:
- c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Function.v.resolve (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:4:760)
	at e.exports (c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js:33:4955)
	at w (c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js:37:850)
	at c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js:37:887
	at Array.map (<anonymous>)
	at E (c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js:37:879)
	at T (c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js:37:2467)
	at async L (c:\Users\ChrisLewis\.vscode\extensions\davidanson.vscode-markdownlint-0.42.1\bundle.js:37:5546)
```

**Comment by DavidAnson** [comment] 2021-07-08 17:47
Duplicate of #158, you can find details and a fix there. It's an issue with the docsmsft-linting extension.

**Comment by DavidAnson** [comment] 2021-07-08 17:48
Well, duplicate of the bottom 3 comments there, not the original issue.

**Closed** 2021-07-08 17:52 UTC
